### ISSUE TITLE
Domain layer needs to be parcelable

### ISSUE THREAD

**Issue by akshaybhange** [SAGARSURI/PixelPerfectNative#1]
Data Classes in Domain layer needs to be parcelable in order to pass between activities/fragments.

**Comment by SAGARSURI** [comment]
Yeah that is required. I didn’t do till now coz I didn’t find the usecase for it now. But in future yes I have to.

**Comment by akshaybhange** [comment]
When we declare domain layer entities parcelable, we will need to convert this module from "java-library" to android library or something. How to handle this case? You don't need that in this case but please help me solve this issue.

**Comment by SAGARSURI** [comment]
For that, you don't have to convert the module to the android library because `Parcelize`  doesn't depend on android specific APIs.
https://medium.com/@BladeCoder/a-study-of-the-parcelize-feature-from-kotlin-android-extensions-59a5adcd5909

**Comment by SAGARSURI** [comment]
What I can think of is, create a mapper in your app module which will convert the domain layer's data class to `parcelable` data class. @akshaybhange 
If you are facing any difficulty in implementation then let me know.

**Comment by akshaybhange** [comment]
@SAGARSURI we already have a entity in framework layer to get json data & then we pass data to domain layer. Now do I have to have a entity in presentation layer as well ? because 99% data received in framework layer I'm passing in presentation layer. Please help me with mapper as well if we need to create one.

**Comment by SAGARSURI** [comment]
I will update my code repository by tonight with the implementation.

**Comment by SAGARSURI** [comment]
@akshaybhange I have done the changes as you requested. Check the latest commit.

**Comment by akshaybhange** [comment]
@SAGARSURI thank you😊, just one more request. Can you help writing test cases for this project ?

**Comment by SAGARSURI** [comment]
Sure. I will update the repo by tomorrow. Currently working on it.
